### ISSUE TITLE
LocalJumpError after conversion to 12.5-style resources

### ISSUE THREAD

**Issue by nathwill** [chef-cookbooks/httpd#53]
not sure yet exactly what's going wrong here, but we just started hitting this with the latest version of the cookbook

```
    workspaces_console: [2015-10-26T22:50:21+00:00] INFO: template[/etc/httpd-workspaces/conf.modules.d/rewrite.load] owner changed to 0
    workspaces_console: [2015-10-26T22:50:21+00:00] INFO: template[/etc/httpd-workspaces/conf.modules.d/rewrite.load] group changed to 0
    workspaces_console: [2015-10-26T22:50:21+00:00] INFO: template[/etc/httpd-workspaces/conf.modules.d/rewrite.load] mode changed to 644
    workspaces_console: [2015-10-26T22:50:21+00:00] INFO: Processing httpd_module_rhel[php] action create (treehouse-images::httpd line 24)
    workspaces_console:
    workspaces_console: ================================================================================
    workspaces_console: Error executing action `create` on resource 'httpd_module_rhel[php]'
    workspaces_console: ================================================================================
    workspaces_console:
    workspaces_console: LocalJumpError
    workspaces_console: --------------
    workspaces_console: unexpected return
    workspaces_console:
    workspaces_console: Cookbook Trace:
    workspaces_console: ---------------
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/httpd/libraries/httpd_module.rb:28:in `block in <class:HttpdModule>'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:562:in `instance_exec'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:562:in `exec_in_resource'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:302:in `get'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:251:in `call'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:455:in `symbolname'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:80:in `public_send'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:80:in `symbolname'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/httpd/libraries/httpd_module_rhel.rb:47:in `block (2 levels) in <class:HttpdModuleRhel>'
    workspaces_console: /tmp/packer-chef-solo/cookbooks-1/httpd/libraries/httpd_module_rhel.rb:41:in `block in <class:HttpdModuleRhel>'
    workspaces_console:
    workspaces_console: Resource Declaration:
    workspaces_console: ---------------------
    workspaces_console: # In /tmp/packer-chef-solo/cookbooks-0/treehouse-images/recipes/httpd.rb
    workspaces_console:
    workspaces_console: 24: httpd_module 'php' do
    workspaces_console: 25:   instance 'workspaces'
    workspaces_console: 26: end
    workspaces_console: 27:
    workspaces_console:
    workspaces_console: Compiled Resource:
    workspaces_console: ------------------
    workspaces_console: # Declared in /tmp/packer-chef-solo/cookbooks-0/treehouse-images/recipes/httpd.rb:24:in `from_file'
    workspaces_console:
    workspaces_console: httpd_module_rhel("php") do
    workspaces_console: action [:create]
    workspaces_console: retries 0
    workspaces_console: retry_delay 2
    workspaces_console: default_guard_interpreter :default
    workspaces_console: declared_type :httpd_module
    workspaces_console: cookbook_name :"treehouse-images"
    workspaces_console: recipe_name "httpd"
    workspaces_console: instance "workspaces"
    workspaces_console: module_name "php"
    workspaces_console: httpd_version "2.4"
    workspaces_console: package_name "php"
    workspaces_console: end
    workspaces_console:
    workspaces_console: [2015-10-26T22:50:21+00:00] INFO: Running queued delayed notifications before re-raising exception
    workspaces_console: [2015-10-26T22:50:21+00:00] ERROR: Running exception handlers
    workspaces_console: [2015-10-26T22:50:21+00:00] ERROR: Exception handlers complete
    workspaces_console: [2015-10-26T22:50:21+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
```
